stationeryStore/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('store.urls'))
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', productList, name='productListUrl'),
	path('product/search/', productSearch, name='productSearchUrl'),
	path('product/<str:slug>/', productDetail, name='productDetailUrl'),
	path('product/category/<str:slug>/', productCategory, name='productCategoryUrl'),
	path('product/setCount/<str:slug>/', productSetCount, name='productSetCount')
]

store/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField

class Category(models.Model):
	name = models.CharField("Категория", max_length = 255)
	parent = models.ForeignKey('self', verbose_name = "Родитель", on_delete = models.SET_NULL, blank = True, null = True)
	url = models.SlugField("Ссылка", max_length = 150, unique = True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Категория"
		verbose_name_plural = "Категории"

class Product(models.Model):
	name = models.CharField("Название", max_length = 255)
	price = models.DecimalField("Цена", max_digits = 19, decimal_places=2)
	description = models.TextField("Описание")
	url = models.SlugField("Ссылка", max_length = 150, unique = True)
	category = models.ForeignKey(Category, verbose_name = "Категория", on_delete = models.SET_NULL, null = True)
	count = models.IntegerField("Количество")

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['count']
		verbose_name = "Товар"
		verbose_name_plural = "Товары"

class Picture(models.Model):
	product = models.ForeignKey(Product, verbose_name = "Товар", on_delete = models.CASCADE)
	description = models.TextField("Описание")
	name = models.CharField("Заголовок", max_length = 255)
	image = models.ImageField("Изображение", upload_to="images/")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Изображение"
		verbose_name_plural = "Изображения"

class Value(models.Model):
	value = models.CharField("Значение", max_length = 100)

	def __str__(self):
		return self.value

	class Meta:
		verbose_name = "Значение"
		verbose_name_plural = "Значения"

class Feature(models.Model):
	name = models.CharField("Название", max_length = 255)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Характеристика"
		verbose_name_plural = "Характеристики"

class ProductFeatureValue(models.Model):
	product = models.ForeignKey(Product, verbose_name = "Товар", on_delete = models.CASCADE)
	feature = models.ForeignKey(Feature, verbose_name = "Характеристика", on_delete = models.CASCADE)
	value = models.ForeignKey(Value, verbose_name = "Значение", on_delete = models.CASCADE)

	class Meta:
		verbose_name = "Характеристика товара"
		verbose_name_plural = "Характеристики товаров"

store/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.core.paginator import Paginator
from django.db.models import Q

from store.models import *

itemOnThePage = 6

def isAuth(request):
    if not request.user.is_authenticated and not request.user.is_staff:
        return False
    return True

def pagination(products, itemPage, pageNumber):
	paginator = Paginator(products, itemOnThePage)
	page = paginator.get_page(pageNumber)
	isPaginated = page.has_other_pages()

	if page.has_previous():
		prevUrl = '?page={}'.format(page.previous_page_number())
	else:
		prevUrl = ''

	if page.has_next():
		nextUrl = '?page={}'.format(page.next_page_number())
	else:
		nextUrl = ''

	return {'nextUrl': nextUrl, 'prevUrl': prevUrl, 'page': page, 'isPaginated': isPaginated}

def productList(request, products=None, categoryName=''):

	if products is None:
		products = Product.objects.all()

	categories = Category.objects.filter(parent__isnull=True) #categories which don't have parent

	pageNumber = request.GET.get('page', 1)
	contextPages = pagination(products, itemOnThePage, pageNumber)

	return render(request, 'store/products_list.html', {'categories_list': categories,
														'category_name': categoryName,
														'nextUrl': contextPages['nextUrl'], 
														'prevUrl': contextPages['prevUrl'],
														'page_object': contextPages['page'], 
														'isPaginated': contextPages['isPaginated']})

def productCategory(request, slug):
	category = Category.objects.get(url__iexact = slug)
	categoryName = category.name
	products = category.product_set.all()
	return productList(request, products=products, categoryName=categoryName)

def productSearch(request):
	searchQuery = request.GET.get('search', '')
	products = Product.objects.filter(Q(name__icontains=searchQuery) | Q(description__icontains=searchQuery))
	return productList(request, products=products)

def productDetail(request, slug):
	product = Product.objects.get(url__iexact = slug)
	return render(request, 'store/product_detail.html', {'product': product})

def productSetCount(request, slug):
    count = request.POST.get('count');
    product = Product.objects.get(url__iexact = slug)
    if isAuth(request):
        product.count = count;
        product.save();
        return redirect('productListUrl')
    else:
        return HttpResponse('<h1>ERROR 403</h1>')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
	{% block customCSS %}

	{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<title>
		{% block title %}

		{% endblock %}
	</title>
</head>
<body>
	{% include 'include/header.html' %}

	{% block content %}

	{% endblock %}

	{% include 'include/footer.html' %}
</body>
</html>

templates/include/footer.html
<footer>
	<a href="https://github.com/kirill568">Разработчик</a>
</footer>

templates/include/header.html
<header>
	<a href="{% url 'productListUrl' %}"><h1>Stationery catalog</h1></a>
</header>

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}


{% block customCSS %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick/slick.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick/slick-theme.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/productCard.css' %}">
{% endblock %}

{% block title%}
	{{ product.name }}
{% endblock %}

{% block content %}
	<section class="card">
		<div class="product">
			<div class="images">
				<div class="sliderFor">
					{% for image in product.picture_set.all %}
						<img src="{{ image.image.url }}">
					{% endfor %}
				</div>			
				<div class="sliderNav">
					{% for image in product.picture_set.all %}
						<img src="{{ image.image.url }}">
					{% endfor %}
				</div>
			</div>

			<div class="info">
				<div class="name">
					<h2>{{ product.name }}</h2>
				</div>

				<div class="description">
					{{ product.description }}
				</div>		
			</div>

			<div class="price">
					{{ product.price }}
					{% if request.user.is_authenticated and request.user.is_staff %}
						<form action="{% url 'productSetCount' slug=product.url %}" method="post"> 
							{% csrf_token %}
							<input style="max-width: 50px;" type="number" name="count" value="{{ product.count }}">
							<input type="submit" name="setCount" value="Обновить" class="btn btnSetCount">
						</form>
					{% else %}
						<span><b>{{ product.count }}</b></span>
					{% endif %}
			</div>
		</div>

		<div class="features">
			<table>
				<caption>Хакартеристики</caption>
				{% for feature in product.productfeaturevalue_set.all %}
					<tr>
						<td>{{ feature.feature.name }}</td>
						<td>{{ feature.value.value }}</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</section>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/slick/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script/slider.js' %}"></script>
{% endblock %}

templates/store/products_list.html
{% extends 'base.html' %}
{% load static %}


{% block customCSS %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/productList.css' %}">
{% endblock %}

{% block title%}
	Главная
{% endblock %}
{% block content %}
<section class="main">
	<aside class="tools">
		<div class="categories">
			<ul>
				{% for category in categories_list %}
					<li class="{% if category.category_set.all%}parent{% endif %}">
						<a href="{% url 'productCategoryUrl' slug=category.url %}">{{ category.name }}</a>
						<ul class="child">
							{% for cat in category.category_set.all %}
								<li><a href="{% url 'productCategoryUrl' slug=cat.url %}">{{ cat.name }}</a></li>
							{% endfor %}
						</ul>
					</li>
				{% endfor %}
			</ul>
		</div>

		<div class="filters">

			<form action="{% url 'productSearchUrl' %}" method="get">
				<input type="text" name="search">

				<input type="submit" name="searchButton" value="найти" class="btn btnSearch">
			</form>

			<!-- <form action="{% url 'productListUrl' %}" method="get">
				{% for feature in feature_values %}
					<div class="filter">
						<p class="titleFilter">{{ feature.featureName }}</p>

						{% for value in feature.values %}

							<input type="checkbox" name="{{ feature.featureNameLang }}" value="{{ value.value }}" id="{{ value.value }}">
							<label for="{{ value.value }}">{{ value.value }}</label><br>

						{% endfor %}
					</div>
				{% endfor %}
				<input type="submit" value="применить фильтры" class="btn btnFilters">
			</form> -->
		</div>
	</aside>

	<div class="productList">
		<div class="currentCategory">
			Текущая категория: {% if category_name %} {{ category_name }} {% else %} Главная {% endif %}
		</div>
		{% for product in page_object.object_list %}
			<div class="product">
				<div class="imageWrapper">
					<img src="{{ product.picture_set.first.image.url }}">
				</div>
				<div class="productInfo">					
					<p class="productName">{{ product.name }}</p>
					<span class="price">{{ product.price }}</span>
					<div class="productCount"><span>Количество товара на складе:</span>
						{% if request.user.is_authenticated and request.user.is_staff %}
							<form action="{% url 'productSetCount' slug=product.url %}" method="post"> 
								{% csrf_token %}
								<input style="max-width: 50px;" type="number" name="count" value="{{ product.count }}">
								<input type="submit" name="setCount" value="Обновить" class="btn btnSetCount">
							</form>
						{% else %}
							<span><b>{{ product.count }}</b></span>
						{% endif %}
					</div>
				</div>
				<a class="btnOpen" href="{% url 'productDetailUrl' slug=product.url %}">Открыть</a>			
			</div>
		{% endfor %}
	</div>
</section>

<section class="paginationWrapper">
	{% if isPaginated %}
		<div class="pagination">
			<a href="{{ prevUrl }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" class="page preUrl {% if not prevUrl %}disabled{% endif %}">&laquo;</a>
			{% for n in page_object.paginator.page_range %}
				{% if page_object.number == n %}
					<a href="?page={{ n  }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" class="page active">{{ n }}</a>
				{% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
					<a href="?page={{ n  }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" class="page">{{ n }}</a>
				{% endif %}
			{% endfor %}
			<a href="{{ nextUrl }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" class="page nextUrl {% if not nextUrl %}disabled{% endif %}">&raquo;</a>
		</div>
	{% endif %}
</section>
{% endblock %}